spring:
   datasource:
       password: root
       url: jdbc:mysql://127.0.0.1:3306/dbsunny?createDatabaseIfNotExist=true
       username: root
   jpa:
       database-platform: org.hibernate.dialect.MySQLDialect
       hibernate:
           ddl-auto: create
       show-sql: true
